### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by AshiswhoIam** [bananaslamjamma/SOEN_341#56]
Story Description: As a user I want to be able to search for specific questions.
Story Points: 30 points
Risk: High Risk, High Value
Priority: A potentially valued sub feature 

Task breakdown:
1) Create a search bar in the nav bar #75
2) Create a function to search specific wordings #76
3) Create a database of all questions #62 

Acceptance Testing for the user stories:
Test{
-Have a nav bar to enter information to search
-Type information
-Hit enter
-Display of questions/answers based on the information typed
Steps not finished user story incomplete
}

**Comment by bananaslamjamma** [comment]
completed
