### ISSUE TITLE
Multiple Voting

### ISSUE THREAD

**Issue by AshiswhoIam** [bananaslamjamma/SOEN_341#57]
Story Description: As services providers we want users to be able to vote only once to provide a sense of equality.
Story Points: 20 points
Risk: Low Risk, High Value
Priority: An important functionality of  one of the main core features to take priority.

Task Breakdown:
1) Create a storing for upvote numbers unique to users id #65

Acceptance Testing for the user stories:
Test{
-Go to the forum
-Upvote an answer
-Counter goes up
-Reset and try to upvote again on the same answer
-Counter stays
-Downvote an answer
-Counter goes down
-Reset and try to upvote downvote on the same answer
-Counter stays
Steps not finished user story incomplete
}

**Comment by bananaslamjamma** [comment]
Done, votes are stored per individual, one vote per user.
