### ISSUE TITLE
Creating the information Section

### ISSUE THREAD

**Issue by AshiswhoIam** [bananaslamjamma/SOEN_341#58]
Story Description: As a user I want access to the information on the developers that built the website.
Story Points: 5 points
Risk: Low Risk, Low Value
Priority: Of minimal importance for now.

Task breakdown: 
1) Create a nav bar to switch pages #65
2) Create a new page to display information of team #78

Acceptance Testing for the user stories:
Test{
-Have a functional nav bar to switch pages
-Have a display page of the information on the contributors
Steps not finished user story incomplete
}

**Comment by AshiswhoIam** [comment]
We decided to choose the search bar function as our additional feature.

**Comment by bananaslamjamma** [comment]
closed, see above
